model: "dual_model"  # Which model to train
version: "0.0.0" # Should be used when changing parameters, preprocessing etc.
params:  # Additional model parameters
  agg_method: "max"  # How to aggregate the predictions of the two models. Options: "mean", "max"
  model1: # Each model must have already been trained and saved in that base path
    name: "cosine_sim"
    version: "0.0.0"
    params:  # Additional model1 parameters
      dummy: 0
  model2: # Each model must have already been trained and saved in that base path
    name: "cocitation_logistic"
    version: "0.0.0"
    params:  # Additional model2 parameters
      dummy: 0