ranker: "random"  # Which model to train
version: "0.0.0"  # Should be used when changing parameters, preprocessing etc.
params:  # Additional ranker parameters, random ranker doesn't have any
  dummy: 0
