data_queries:
  kaggle_json_to_parquet: False
  query_papers: False
  query_authors: False
  generate_samples: False
paper_embedding:
  fit: False
train: False
eval: False
ranking:
  generate_samples: False
  generate_predictions: False
  generate_paper_embeddings: False
  evaluate: True
