data:
  kaggle_json_to_parquet: True  # Prerequisite: None
  process_papers: True  # Prerequisite: data/kaggle_json_to_parquet
  process_citations: True  # Prerequisite: data/process_papers
  process_citing_papers: True  # Prerequisite: data/process_citations
  unify_papers: True  # Prerequisite: data/process_citing_papers
  process_authors: True  # Prerequisite: data/process_citing_papers
  generate_samples: True  # Prerequisite: data/process_authors & data/unify_papers
data_queries:
  kaggle_json_to_parquet: False  # Prerequisite: None
  query_papers: False  # Prerequisite: data_queries/kaggle_json_to_parquet
  query_authors: False  # Prerequisite: data_queries/query_papers
  generate_samples: False  # Prerequisite: data_queries/query_authors
paper_embedding:
  fit: False  # Prerequisite: data_queries
model:
  train: False  # Prerequisite: data_queries
  eval: False  # Prerequisite: model/train
ranking:
  generate_samples: False  # Prerequisite: data_queries
  generate_predictions: False  # Prerequisite: ranking/generate_samples & model/train
  generate_paper_embeddings: False  # Prerequisite: ranking/generate_samples & paper_embedding/fit
  evaluate: False  # Prerequisite: ranking/generate_predictions & ranking/generate_paper_embeddings
