data_queries:
  kaggle_json_to_parquet: True
  query_papers: True
  query_authors: True
  generate_samples: True
train: True
eval: True
ranking:
  generate_sample: False
  generate_predictions: False
  evaluate: False
