data_queries:
  kaggle_json_to_parquet: False
  query_papers: False
  query_authors: False
  generate_samples: False
train: False
eval: False
ranking:
  generate_sample: False
  generate_predictions: False
  evaluate: True
