data:
  kaggle_json_to_parquet: True  # Prerequisite: None
  process_papers: True  # Prerequisite: data/kaggle_json_to_parquet
  process_citations: True  # Prerequisite: data/process_papers
  process_citing_papers: True  # Prerequisite: data/process_citations
  process_authors: True  # Prerequisite: data/process_citing_papers
  get_abstracts: True  # Prerequisite: data/process_citing_papers
  unify_papers: True  # Prerequisite: data/process_authors & data/get_abstracts
  process_references: True  # Prerequisite: data/unify_papers
  generate_samples: True  # Prerequisite: data/process_references
matrix:
  generate_citation_matrix: True # Prerequisite: data
paper_embedding:
  fit: True  # Prerequisite: data
model:
  train: True  # Prerequisite: data, and also matrix if using matrix-based models
  eval: True  # Prerequisite: model/train
ranking:
  generate_samples: True  # Prerequisite: data
  generate_predictions: True  # Prerequisite: ranking/generate_samples & model/train
  generate_paper_embeddings: True  # Prerequisite: ranking/generate_samples & paper_embedding/fit
  evaluate: True  # Prerequisite: ranking/generate_predictions & ranking/generate_paper_embeddings
